### ISSUE TITLE
Why the performance of these methods is much lower than they claimed?

### ISSUE THREAD

**Issue by mrbeann** [OpenGSL/OpenGSL#25]
Thanks for this Nice work. I found the results here are much lower than they claimed in the same dataset (e.g., in NodeFormer uses 20 labels per class for training the accuracy is 83.4, and OpenGSL is 78.81). Is there any idea why this happened?

**Comment by zzysh12345** [comment]
83.4 mentioned here comes from random split, while we chose to use fixed split in our work. Besides our own implementation, we ran the source code using the script provided by [Nodeformer,](https://github.com/qitianwu/NodeFormer/blob/main/run_extra.sh) (line 16) and the result was close to 78.81.

**Comment by mrbeann** [comment]
Thanks for the quick reply, it looks like the random division here makes a big difference. I am curious whether different divisions will lead to differences in the conclusions in the paper? Especially for NodeFormer, it seems that he is not as simple as the simplest method

**Comment by zzysh12345** [comment]
Different splits can make a difference, especially for small datasets like cora, as they may result in different distributions of supervised information. This issue has been identified in some previous works. In the future, we plan to incorporate more reliable datasets. As for Nodeformer, I suggest that it may be more suitable for scenarios with abundant supervised information due to its transformer architecture without inductive bias. We will explore this aspect further in the future.

**Comment by mrbeann** [comment]
Thank you for your reply. It's interesting to know this. And looking forward to the updates of OpenGSL.
